$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
job_name: opengrid_drawer_floor
scene:
  blend_file: ../assets/scenes/opengrid_floor_scene.blend
  objects:
  - id: drawer_container
    model:
      scad_file: openconnect_drawer.scad
      defines:
        generate_drawer_shell: false
        generate_drawer_container: true
        add_container_divider: Both
        container_width_grid_count: 3
        container_width_compartment_list: "2,1"
        container_depth_grid_count: 5
        container_depth_compartment_list: "1,2,2"
        container_front_wall_type: Solid
        container_side_wall_type: Solid
    transform:
      location_mm: [0, 0, 0]
      rotation_deg: [0, 0, 0]
render:
  fit_margin: 0.2
  camera_view_preset: top_front
annotations:
  object: drawer_container
  style:
    $constant: default_annotation_style
    image_label_title_positions: [top, bottom]
    image_label_title_top_margin_px: 18
    image_label_title_bottom_margin_px: 6  # box distance from bottom image edge
    image_label_title_padding_x_px: 20       # horizontal padding inside box
    image_label_title_padding_y_px: 6     # vertical padding inside box
    image_label_title_min_width_px: 620      # minimum box width
  # chains:
  # - ids: [horizontal_grids]
  #   label_offset_px: 42
  # - ids: [vertical_grids]
  #   line_offset_px: 30
  #   label_offset_px: 30
  #   label_font_size_px:
  #     $constant: annotation_label_font_size_px
  # - ids: [depth_grids]
  #   line_offset_px: 30
  #   label_offset_px: 30
  image_labels:
  - $constant: bottom_image_label
    id: container_width_grid_count
    offset_px: [0, 00]
    show_value: true
    value_color: '#ff0000'
    font_size_px: 30
  - $constant: bottom_image_label
    id: container_width_compartment_list
    offset_px: [0, 30]
    show_value: true
    value_color: '#ff0000'
    font_size_px: 30
  - $constant: bottom_image_label
    id: container_depth_grid_count
    offset_px: [0, 70]
    show_value: true
    value_color: '#ff0000'
    font_size_px: 30
  - $constant: bottom_image_label
    id: container_depth_compartment_list
    offset_px: [0, 100]
    show_value: true
    value_color: '#ff0000'
    font_size_px: 30
  - id: add_container_divider
    position: top
    offset_px: [0, 0]
    show_value: true
    value_color: '#2563eb'
    font_size_px: 36
