$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_configs:
- openconnect_sturdy_hook.yaml
- openconnect_sturdy_shelf.yaml
- openconnect_gridfinity_shelf.yaml
- openconnect_general_holder.yaml
- openconnect_vasemode_container.yaml
- openconnect_clamshell_holder.yaml
- path: openconnect_drawer_shell_container.yaml
  variant: shell
  name: openconnect_drawer_shell
- openconnect_drawer_shell_container.yaml
- openconnect_standard_snap_grid_copies.yaml
- opengrid_expanding_standard_snap_grid_copies.yaml
- opengrid_framefit_hook.yaml
- opengrid_snap_gadget_hook.yaml
- opengrid_snap_gadget_clip.yaml
- opengrid_snap_gadget_plier_holder.yaml
