$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
job_name: opengrid_annotation_models
variant_configs:
- openconnect_sturdy_hook_default.yaml
- openconnect_sturdy_shelf_default.yaml
- openconnect_gridfinity_shelf_default.yaml
- openconnect_general_holder_default.yaml
- openconnect_vasemode_container_default.yaml
- openconnect_clamshell_holder_default.yaml
- path: openconnect_drawer_shell_container_default.yaml
  variant: shell
  name: openconnect_drawer_shell_default
- openconnect_drawer_shell_container_default.yaml
- openconnect_standard_snap_grid_copies.yaml
- opengrid_expanding_standard_snap_grid_copies.yaml
- opengrid_framefit_hook_default.yaml
- opengrid_snap_gadget_hook_default.yaml
- opengrid_snap_gadget_clip_default.yaml
- opengrid_snap_gadget_plier_holder_default.yaml
