$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: opengrid_framefit_hook_default
job_name: framefit_hook_scene
scene:
  objects:
  - id: model
    model:
      scad_file: opengrid_framefit_hook.scad
      defines:
        hook_length: 28
        hook_tip_length: 10
    transform:
      location_mm: [0, 0, "-(2 * og_tile_size)"]
      rotation_deg: [0, 0, 180]
  - id: large_hook
    model:
      scad_file: opengrid_framefit_hook.scad
      defines:
        hook_width: 7
        hook_corner_angle: 45
        hook_tip_angle: 90
        hook_length: 16
        hook_tip_length: 6
    transform:
      location_mm: [og_tile_size, 0, "-(2 * og_tile_size)"]
      rotation_deg: [0, 0, 180]
  - id: truss_hook
    model:
      scad_file: opengrid_framefit_hook.scad
      defines:
        hook_width: 10
        hook_length: 32
        hook_tip_length: 12
        truss_vertical_grids: 1
    transform:
      location_mm: ["-og_tile_size", 0, "-(2 * og_tile_size)"]
      rotation_deg: [0, 0, 180]
render:
  fit_margin: 0
  # camera_view_preset: back_left
annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: true
    type_styles:
      grids:
        line_colors:
        - $constant: annotation_color_blue
      mm:
        line_colors:
        - $constant: annotation_color_black
  aliases:
    hook_vertical_grids: "hook_vGrids x {og_tile_size:g}mm"
    truss_vertical_grids: "truss_vertical_grids x {og_tile_size:g}mm"
    hook_tip_shape: hook_tip_shape
  chains:
  - ids: [hook_width]
    display_offset_mm: [0, 0, 0]
    line_offset_px: 40
    label_offset_px: 50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [hook_length]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -60
    label_offset_px: -50
    label_font_size_px: 52
  # - ids: [hook_back_thickness]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: -50
  #   label_offset_px: -50
  #   label_font_size_px: 24
  # - ids: [hook_tip_length]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: -50
  #   label_offset_px: -50
  #   label_font_size_px: 24
  - ids: [hook_vertical_grids, truss_vertical_grids]
    optional: true
    display_offset_mm: [0, 0, 0]
    line_offset_px: 40
    label_offset_px: 50
    label_font_size_px: 46
