$schema: ../schemas/annotation-render-config.schema.json
extends: openconnect_sturdy_hook_empty.yaml
job_name: sturdy_hook_parameter_gallery

gallery:
  columns: 2
  target_width_px: 1920
  target_height_px: 1440
  margin_px: 0
  gutter_px: 4
  title_height_px: 60
  title_font_size_px: 60

variants:
- name: SliceOff_Target14
  set:
    # scene.objects[0].model.defines.truss_vertical_grids: 1
    scene.objects[0].model.defines.circular_tip_thickness_scale: 1
    scene.objects[0].model.defines.hook_tip_sliceoff_side: Left
    scene.objects[0].model.defines.hook_tip_sliceoff_target_width: 14
    # scene.objects[0].model.defines.hook_length: 70

- name: Rectangular
  set:
    scene.objects[0].model.defines.hook_shape_type: Rectangular
    scene.objects[0].model.defines.rectangular_tip_extra_length: 10
    scene.objects[0].model.defines.hook_corner_fillet: 0
    scene.objects[0].model.defines.hook_length: 46

- name: Flat
  set:
    scene.objects[0].model.defines.hook_shape_type: Flat
    scene.objects[0].model.defines.hook_corner_fillet: 0
    scene.objects[0].model.defines.hook_length: 46

- name: TrussGrid1
  set:
    scene.objects[0].model.defines.truss_vertical_grids: 1
    # scene.objects[0].model.defines.hook_length: 70
