$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: opengrid_snap_gadget_hook_default
job_name: snap_gadget_hook_scene
scene:
  objects:
  - id: model
    model:
      scad_file: opengrid_snap_gadget_hook.scad
      defines:
        hook_main_size: 30
        hook_thickness_scale: 1
        hook_tip_angle: 180
    transform:
      location_mm: [-14, 0, -20.6]
      rotation_deg: [0, 0, 0]
  - id: snap_a
    $constant: expanding_snap_object
    transform:
      location_mm: [-14, 0, -14]
      rotation_deg: [-90, 180, 0]
render:
  fit_margin: 0
  camera_view: top
  lighting:
    toplight_power: 2
    # frontlight_power: 1.5
annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: false
    
    type_styles:
      mm:
        line_colors:
        - $constant: annotation_color_black
  angle_radius_callouts:
  - id: hook_tip_angle_detail
    arc_id: hook_tip_angle_extent
    radius_id: hook_tip_angle_radius
    angle_id: hook_tip_angle
    display_offset_mm: [-2, 0, 0]
    optional: true
    show_radius_label: false
    angle_label_offset_px: 80
    # angle_label_tangent_offset_px: 56
    angle_fill_alpha: 28
  chains:
  # - ids: [hook_width]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 28
  #   label_offset_px: 28
  #   label_font_size_px: 24
  - ids: [hook_thickness]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -50
    label_offset_px: -50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [hook_main_size]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -320
    label_offset_px: -50
    label_along_offset_px: 90
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [hook_stem_length]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -320
    label_offset_px: -50
    label_along_offset_px: -90
    label_font_size_px:
      $constant: annotation_label_font_size_px
    color: 
      $constant: annotation_color_blue
