$schema: ../schemas/annotation-render-config.schema.json
extends: animation_presets.yaml
variant_name: openconnect_sturdy_shelf_default
job_name: sturdy_shelf_scene_default
scene:
  objects:
  - id: model
    model:
      scad_file: openconnect_sturdy_shelf.scad
      defines:
        shelf_type: Standard
        add_texture: true
    transform:
      location_mm: [56, 0, -28]
  transform:
    $constant: wall_placeholder_transform
render:
  fit_margin: 0
  # camera_view: right
annotations:
  style:
    $constant: default_annotation_style
  aliases:
    $constant: default_grid_label_aliases
  chains:
  - ids: [depth_grids]
    line_offset_px: 0
    label_offset_px: -50
    label_font_size_px:
      $constant: annotation_label_font_size_px
    color:
      $constant: annotation_color_black
  - ids: [horizontal_grids]
    line_offset_px: 0
    label_offset_px: 50
    label_font_size_px:
      $constant: annotation_label_font_size_px
    color:
      $constant: annotation_color_black
  # - $constant: small_dimension_chain
  #   ids: [shelf_back_thickness]
  # - $constant: small_dimension_chain
  #   ids: [shelf_bottom_thickness]
  # image_labels:
  # - $constant: bottom_image_label
  #   id: shelf_type
  #   show_value: true
