$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: openconnect_general_holder_default
job_name: general_holder_scene_default
scene:
  objects:
  - id: model_a
    model:
      scad_file: openconnect_general_holder.scad
      defines:
        compartment_column_count: 1
        compartment_row_count: 1
        compartment_corner_rounding: 5
        holder_back_offset: 0
    transform:
      location_mm: [0, 0, -28]
      rotation_deg: [holder_tilt_angle, 0, 0]
      scale:
        $constant: blender_scene_scale_vector
  # - id: model_b
  #   model:
  #     scad_file: openconnect_general_holder.scad
  #     defines:
  #       compartment_shape: Circular
  #       compartment_column_count: 1
  #       compartment_row_count: 1
  #       enable_bottom_taper: true
  #       front_opening_height: 60
  #   transform:
  #     location_mm: [112, 0, -28]
  #     rotation_deg: [holder_tilt_angle, 0, 0]
  #     scale:
  #       $constant: blender_scene_scale_vector
render:
  fit_margin: 0
  camera_view: top
  # camera_location_offset_mm: [0, 0, 100]
  # camera_look_at: object_center
  # camera_view_preset: top_front
annotations:
  style:
    auto_adjust_labels: true
    $constant: default_annotation_style
  aliases:
    holder_outer_wall_thickness: outer_wall_thickness
  chains:
  - ids: [compartment_width]
    color:
      $constant: annotation_color_black
    line_offset_px: 50
    label_offset_px: 28
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [compartment_depth]
    optional: true
    color:
      $constant: annotation_color_black
    line_offset_px: -50
    label_offset_px: -28
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [holder_back_offset]
    optional: true
    line_offset_px: -40
    label_offset_px: -28
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [holder_outer_wall_thickness]
    optional: true
    display_offset_mm: [0, 0, 0]
    line_offset_px: -50
    label_offset_px: -28
    label_font_size_px:
      $constant: annotation_label_font_size_px
  # - ids: [front_opening_width]
  #   optional: true
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 20
  #   label_offset_px: 28
  #   font_size_px: 26
  radius_callouts:
  - ids: [compartment_corner_rounding]
    optional: true
    label_offset_px: -120
    label_font_size_px:
      $constant: annotation_label_font_size_px
  arc_callouts:
  - ids: [compartment_corner_rounding_extent]
    optional: true
    show_label: false
  # - ids: [front_opening_height]
  #   optional: true
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 24
  # angle_radius_callouts:
  # - id: holder_tilt_angle_callout
  #   arc_id: holder_tilt_angle_extent
  #   radius_id: holder_tilt_angle_radius
  #   angle_id: holder_tilt_angle
  #   optional: true
  #   show_radius_label: false
  #   angle_label_offset_px: 34
  #   angle_fill_alpha: 28
  # image_labels:
  # - $constant: bottom_image_label
  #   id: compartment_shape
  #   offset_px: [0, 0]
  #   show_value: true
  #   value_color: '#0000FF'
  #   font_size_px:
  #     $constant: annotation_title_font_size_px
