$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: opengrid_snap_gadget_clip_default
job_name: snap_gadget_clip_scene
scene:
  objects:
  - id: clip_a
    model:
      scad_file: opengrid_snap_gadget_clip.scad
      defines:
        clip_shape: Rectangular
        clip_main_width: 30
        clip_main_depth: 12
        tip_diameter: 0
        clip_surround_angle: 145
        clip_thickness_scale: 1
    transform:
      location_mm: [-14, 0, -20.6]
      rotation_deg: [0, 0, 0]
  - id: snap_a
    $constant: expanding_snap_object
    transform:
      location_mm: [-14, 0, -14]
      rotation_deg: [-90, 180, 0]
  - id: clip_b
    model:
      scad_file: opengrid_snap_gadget_clip.scad
      defines:
        # clip_shape: Elliptic
        # clip_main_depth: 25
        knurling_type: Diamond
    transform:
      location_mm: [42, 0, -20.6]
      rotation_deg: [0, 0, 0]
  - id: snap_b
    $constant: expanding_snap_object
    transform:
      location_mm: [42, 0, -14]
      rotation_deg: [-90, 180, 0]
  # - id: clip_c
  #   model:
  #     scad_file: opengrid_snap_gadget_clip.scad
  #     defines:
  #       clip_shape: Circular
  #       clip_orientation: Vertical
  #       clip_entry_tilt_angle: 45
  #       # clip_main_depth: 25
  #       # knurling_type: Diamond
  #   transform:
  #     location_mm: [-42, 0, -20.6]
  #     rotation_deg: [0, 90, 0]
  # - id: snap_c
  #   $constant: expanding_snap_object
  #   transform:
  #     location_mm: [-42, 0, -14]
  #     rotation_deg: [-90, 180, 0]
render:
  fit_margin: 0
  # camera_location_offset_mm: [-15, 0, 0]
  # camera_rotation_offset_deg: [0, 0, 5]
annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: true
    type_styles:
      mm:
        line_colors:
        - $constant: annotation_color_black
  chains:
  - ids: [clip_main_width]
    display_offset_mm: [0, 0, 0]
    line_offset_px: 20
    label_offset_px: 50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  # - ids: [clip_main_depth]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: -0
  #   label_offset_px: 56
  #   label_font_size_px: 24
  # - ids: [clip_thickness]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: -0
  #   label_offset_px: -28
  #   label_font_size_px: 24
  - ids: [clip_height]
    display_offset_mm: [0, 0, 0]
    line_offset_px: 50
    label_offset_px: 50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  # angle_radius_callouts:
  # - id: clip_surround_angle_detail
  #   arc_id: clip_surround_angle
  #   radius_id: clip_surround_angle_radius
  #   optional: true
  #   show_radius_label: false
  #   angle_label_offset_px: 90
  #   angle_label_tangent_offset_px: 72
  #   label_font_size_px: 20
  #   auto_adjust_labels: false
  #   angle_fill_alpha: 28
