$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: opengrid_snap_gadget_hook_default
job_name: snap_gadget_hook_scene
scene:
  objects:
  - id: model_a
    model:
      scad_file: opengrid_snap_gadget_hook.scad
      defines:
        hook_main_size: 35
    transform:
      location_mm: [-14, 0, -20.6]
      rotation_deg: [0, 0, 0]
  - id: snap_a
    $constant: expanding_snap_object
    transform:
      location_mm: [-14, 0, -14]
      rotation_deg: [-90, -90, 0]
  - id: model_b
    model:
      scad_file: opengrid_snap_gadget_hook.scad
      defines:
        hook_main_size: 20
        hook_stem_length: 3
        corner_type: Rectangular
    transform:
      location_mm: [42, 0, -20.6]
      rotation_deg: [0, 0, 0]
  - id: snap_b
    $constant: expanding_snap_object
    transform:
      location_mm: [42, 0, -14]
      rotation_deg: [-90, -90, 0]
render:
  fit_margin: 0
  # camera_view_preset: technical_iso
  camera_view_preset: top_front
  # camera_view: top
  # camera_rotation_offset_deg: [-60, 0, -30]
  export_blend: true
annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: true
    tick_length_px: 12
    type_styles:
      mm:
        line_colors: ['#000000']
  angle_radius_callouts:
  - id: hook_tip_angle_detail
    arc_id: hook_tip_angle_extent
    radius_id: hook_tip_angle_radius
    angle_id: hook_tip_angle
    optional: true
    show_radius_label: false
    angle_label_offset_px: 100
    angle_label_tangent_offset_px: 56
    angle_fill_alpha: 28
  chains:
  - ids: [body_width]
    display_offset_mm: [0, 0, 0]
    line_offset_px: 28
    label_offset_px: 28
    label_font_size_px: 24
  - ids: [body_thickness]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -76
    label_offset_px: -76
    label_font_size_px: 24
  - ids: [hook_main_size]
    display_offset_mm: [0, 0, 0]
    line_offset_px: -34
    label_offset_px: -42
    label_font_size_px: 24
  - ids: [hook_stem_length]
    display_offset_mm: [0, 0, 0]
    line_offset_px: 28
    label_offset_px: 28
    label_font_size_px: 24
