$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
default_variant: wall

scene:
  objects:
  - id: snap
    $constant: expanding_snap_object

render:
  fit_margin: 0.3
  camera_view: bottom

annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: true
    type_styles:
      mm:
        line_colors:
        - $constant: annotation_color_black

variant_collections:
  product_views: [wall, floor]

variants:
- name: wall

- name: floor
  scene:
    blend_file: ../assets/scenes/opengrid_floor_scene.blend
    objects:
    - id: screw
      model:
        $constant: expanding_snap_model
        defines:
          generate_screw: openConnect
          snap_thickness: 4
  render:
    camera_view_preset: top_front
  unset:
  - render.fit_margin
  - render.camera_view
