$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
scene:
  objects:
  - id: openconnect_standard_snap
    stl_file: ../assets/openconnect_standard_snap.stl
    inherit_target_transform: false
    replace_target_object: false
    transform:
      location_mm: ["-(og_tile_size / 2)", og_standard_thickness, "-(og_tile_size / 2)"]
      rotation_deg: [90, 0, 0]
      scale:
        $constant: blender_scene_scale_vector
    grid_copies:
      counts: [2, 1, 2]
      spacing_mm: [og_tile_size, 0, og_tile_size]
render:
  fit_margin: 0.16
annotations: {}
