$schema: ../schemas/annotation-render-config.schema.json
extends: openconnect_vasemode_container_empty.yaml
job_name: vasemode_container_parameter_gallery

gallery:
  columns: 2
  target_width_px: 1920
  target_height_px: 1440
  margin_px: 0
  gutter_px: 4
  title_height_px: 45
  title_font_size_px: 45

variants:

- name: Diagonal_Ribs_Texture
  set:
    scene.objects[0].model.defines.render_vase_print_preview: true
    scene.objects[0].model.defines.vase_surface_texture: diamonds
    scene.objects[0].model.defines.vase_tilt_angle: 0
    scene.objects[0].model.defines.horizontal_grids: 1
- name: Cubes_Texture
  set:
    scene.objects[0].model.defines.render_vase_print_preview: true
    scene.objects[0].model.defines.vase_surface_texture: cubes
    scene.objects[0].model.defines.vase_tilt_angle: 0
    scene.objects[0].model.defines.horizontal_grids: 1
- name: Wave_Ribs_Texture
  set:
    scene.objects[0].model.defines.render_vase_print_preview: true
    scene.objects[0].model.defines.vase_surface_texture: wave_ribs
    scene.objects[0].model.defines.vase_tilt_angle: 0
    scene.objects[0].model.defines.horizontal_grids: 1
    # scene.objects[0].transform.location_mm: [0, "-(item_depth + og_standard_thickness)", -14]

- name: No_Texture
  set:
    scene.objects[0].model.defines.render_vase_print_preview: true
    scene.objects[0].model.defines.vase_surface_texture: ""
    scene.objects[0].model.defines.vase_tilt_angle: 0
    scene.objects[0].model.defines.horizontal_grids: 1
    # scene.objects[0].transform.location_mm: [0, "-(item_depth + og_standard_thickness)", -14]
