$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: openconnect_gridfinity_shelf_default
job_name: gridfinity_shelf_scene_default
scene:
  objects:
  - id: model
    model:
      scad_file: openconnect_gridfinity_shelf.scad
      defines:
        gridfinity_width_grids: 2
        gridfinity_depth_grids: 2
        magnet_position: None
        # shelf_back_offset: 4
        # shelf_side_rim: 4
        # shelf_side_rim: 4
        # shelf_front_rim: 4
        # shelf_rim_lip_height: 3
        # magnet_position: Corners Only
    transform:
      location_mm: [-28, 0, -28]
      rotation_deg: [-print_bottom_angle, 0, 0]
  # - id: model_b
  #   model:
  #     scad_file: openconnect_gridfinity_shelf.scad
  #     defines:
  #       gridfinity_width_grids: 4
  #       gridfinity_depth_grids: 2
  #       # shelf_back_offset: 4
  #       # shelf_side_rim: 4
  #       # shelf_side_rim: 4
  #       # shelf_front_rim: 4
  #       # shelf_rim_lip_height: 3
  #       magnet_position: All
  #   transform:
  #     location_mm: [-28, 0, -84]
  #     rotation_deg: [-print_bottom_angle, 0, 0]
render:
  fit_margin: 0
  camera_view_preset: front_right
  # camera_view_preset: technical_iso
  # lighting:
    # preset: technical
    # strength: 0.01
    # ambient_strength: 1
    # color: '#ffffff'
annotations:
  style:
    $constant: default_annotation_style
    auto_adjust_labels: true
  aliases:
    gridfinity_width_grids: gridfinity_width_grids x 42mm
    gridfinity_depth_grids: gridfinity_depth_grids x 42mm
  chains:
  - ids: [gridfinity_width_grids]
    color:
      $constant: annotation_color_black
    line_offset_px: -50
    label_offset_px: -50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [gridfinity_depth_grids]
    color:
      $constant: annotation_color_black
    line_offset_px: -150
    label_offset_px: -50
    label_font_size_px:
      $constant: annotation_label_font_size_px
  - ids: [shelf_back_offset]
    optional: true
    color:
      $constant: annotation_color_red
    line_offset_px: -86
    label_offset_px: -78
    label_along_offset_px: 72
    label_font_size_px:
      $constant: annotation_label_font_size_px
    tick_length_px: 12
  # - ids: [shelf_side_rim]
  #   optional: true
  #   line_offset_px: 70
  #   label_offset_px: 46
  #   label_along_offset_px: -52
  #   label_font_size_px: 22
  #   tick_length_px: 12
  # - ids: [shelf_front_rim]
  #   optional: true
  #   line_offset_px: -88
  #   label_offset_px: -54
  #   label_along_offset_px: 42
  #   label_font_size_px: 22
  #   tick_length_px: 12
  # - ids: [shelf_rim_lip_height]
  #   optional: true
  #   line_offset_px: 46
  #   label_offset_px: 28
  #   label_along_offset_px: 36
  #   label_font_size_px: 22
  #   tick_length_px: 12
  image_labels:
  - $constant: bottom_image_label
    id: magnet_position
    offset_px: [0, 0]
    show_value: true
    value_color:
      $constant: annotation_color_blue
    font_size_px:
      $constant: annotation_title_font_size_px
