$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
default_variant: default
scene:
  objects:
  - id: model
    model:
      scad_file: openconnect_clamshell_holder.scad
      defines:
        item_width: 164
        item_height: 60
        item_depth: 30
        item_corner_rounding: 8
        holder_slot_column_limit: 1
    transform:
      location_mm: [0, -(item_depth+holder_thickness+3.72) / 2, -(item_height+holder_thickness*2)
          / 2]
      rotation_deg: [0, 0, 0]
      scale:
        $constant: blender_scene_scale_vector
render:
  fit_margin: 0.1
annotations:
  style:
    $constant: default_annotation_style
  aliases:
    holder_slot_position: slot_position
    item_corner_rounding_extent: item_corner_rounding
  chains:
    item_width_dimension:
      id: item_width
      display_offset_mm: [0, 0, 0]
      line_offset_px: -30
      label_offset_px: -50
      color:
        $constant: annotation_color_black
    item_height_dimension:
      id: item_height
      display_offset_mm: [0, 0, 0]
      line_offset_px: 20
      label_offset_px: 50
      color:
        $constant: annotation_color_black
    item_depth_dimension:
      id: item_depth
      display_offset_mm: [0, 0, 0]
      line_offset_px: 20
      label_offset_px: 50
      color:
        $constant: annotation_color_black
    front_opening_left_right_margin_dimension:
      id: front_opening_left_right_margin
      enabled: false
      optional: true
      display_offset_mm: [0, 0, 0]
      line_offset_px: 50
      label_offset_px: 50
      label_font_size_px: 48
      color:
        $constant: annotation_color_blue
    front_opening_top_bottom_margin_dimension:
      id: front_opening_top_bottom_margin
      enabled: false
      optional: true
      display_offset_mm: [0, 0, 0]
      line_offset_px: -50
      label_offset_px: -50
      label_font_size_px: 48
      color:
        $constant: annotation_color_blue
    side_cutout_top_margin_dimension:
      id: side_cutout_top_margin
      enabled: false
      color:
        $constant: annotation_color_blue
      display_offset_mm: [0, 0, 0]
      line_offset_px: 200
      label_offset_px: 45
      label_along_offset_px: 0
      label_font_size_px: 48
    side_cutout_bottom_margin_dimension:
      id: side_cutout_bottom_margin
      enabled: false
      color:
        $constant: annotation_color_blue
      display_offset_mm: [0, 0, 0]
      line_offset_px: -300
      label_offset_px: -45
      label_along_offset_px: 0
      label_font_size_px: 48
    side_cutout_back_margin_dimension:
      id: side_cutout_back_margin
      enabled: false
      optional: true
      color:
        $constant: annotation_color_red
      display_offset_mm: [0, 0, 0]
      line_offset_px: -300
      label_offset_px: -45
      label_font_size_px: 48
    side_cutout_front_margin_dimension:
      id: side_cutout_front_margin
      enabled: false
      optional: true
      color:
        $constant: annotation_color_red
      display_offset_mm: [0, 0, 0]
      line_offset_px: 60
      label_offset_px: 45
      label_font_size_px: 48
  angle_radius_callouts:
    item_corner_rounding_fillet:
      enabled: false
      arc_id: item_corner_rounding_extent
      radius_id: item_corner_rounding
      angle_id: item_corner_rounding
      optional: true
      show_angle_label: false
      radius_label_offset_px: 100
      angle_fill_alpha: 28
      label_font_size_px: 48
  image_labels:
    holder_slot_position_label:
      $constant: top_image_label
      id: holder_slot_position
      enabled: false
      show_value: true
      value_color:
        $constant: annotation_color_blue
      font_size_px:
        $constant: annotation_title_font_size_px
gallery:
  $constant: parameter_gallery_settings
variant_collections:
  product_views:
  - default
  - alt
  - empty
  - front
  - side
  parameter_gallery: [Width164_Height60_SlotColumn1, Width164_Height60_SlotColumn2,
    Width164_SlotPosition_Top, Width120_Height100_Rounding20]
variants:
- name: default
- name: alt
  object_overrides:
    model:
      model:
        defines:
          holder_slot_position: Front
          slot_slide_direction: Down
      transform:
        location_mm: [0, -(item_height / 2 + og_standard_thickness / 2), 0]
        rotation_deg: [-90, 0, 0]
  annotation_overrides:
    item_width_dimension:
      enabled: false
    item_height_dimension:
      enabled: false
    item_depth_dimension:
      enabled: false
    holder_slot_position_label:
      enabled: true
- name: empty
  annotation_overrides:
    item_width_dimension:
      enabled: false
    item_height_dimension:
      enabled: false
    item_depth_dimension:
      enabled: false
  unset: [scene.objects.model.model.defines, annotations.aliases]
- name: front
  object_overrides:
    model:
      inherit_target_transform: false
  render:
    fit_margin: 0
    camera_view: front
  annotation_overrides:
    item_width_dimension:
      line_offset_px: -28
      label_font_size_px:
        $constant: annotation_label_font_size_px
    item_height_dimension:
      line_offset_px: 50
      label_font_size_px:
        $constant: annotation_label_font_size_px
    item_depth_dimension:
      enabled: false
    front_opening_left_right_margin_dimension:
      enabled: true
    front_opening_top_bottom_margin_dimension:
      enabled: true
    item_corner_rounding_fillet:
      enabled: true
- name: side
  object_overrides:
    model:
      inherit_target_transform: false
      model:
        defines:
          side_cutout_bottom_margin: 20
          side_cutout_top_margin: 10
          side_cutout_back_margin: 5
  render:
    fit_margin: 0
    camera_view: right
  annotation_overrides:
    item_width_dimension:
      enabled: false
    item_height_dimension:
      enabled: false
    item_depth_dimension:
      enabled: false
    front_opening_top_bottom_margin_dimension:
      enabled: true
      optional: false
      line_offset_px: -250
      label_offset_px: -45
      color:
        $constant: annotation_color_black
    side_cutout_top_margin_dimension:
      enabled: true
    side_cutout_bottom_margin_dimension:
      enabled: true
    side_cutout_back_margin_dimension:
      enabled: true
    side_cutout_front_margin_dimension:
      enabled: true
  unset: [annotations.aliases]
- name: Width164_Height60_SlotColumn1
  extends_variant: empty
  object_overrides:
    model:
      model:
        defines:
          item_width: 164
          item_height: 60
          item_corner_rounding: 8
          holder_slot_column_limit: 1
- name: Width164_Height60_SlotColumn2
  extends_variant: empty
  object_overrides:
    model:
      model:
        defines:
          item_width: 164
          item_height: 60
          item_corner_rounding: 8
          holder_slot_column_limit: 2
- name: Width164_SlotPosition_Top
  extends_variant: empty
  object_overrides:
    model:
      model:
        defines:
          item_width: 164
          item_height: 60
          item_corner_rounding: 8
          holder_slot_column_limit: 1
          holder_slot_position: Top
          slot_slide_direction: Down
      transform:
        location_mm: [0, -(item_height+holder_thickness+3.72), -(item_depth+holder_thickness*2)
            / 2]
        rotation_deg: [-90, 0, 0]
- name: Width120_Height100_Rounding20
  extends_variant: empty
  object_overrides:
    model:
      model:
        defines:
          item_width: 120
          item_height: 100
          item_corner_rounding: 20
          holder_slot_column_limit: 1
      transform:
        location_mm: [0, -(item_depth+holder_thickness+3.72) / 2, -(item_height+holder_thickness*2)
            / 2-14]
