$schema: ../schemas/annotation-render-config.schema.json
extends: openconnect_sturdy_shelf_empty.yaml
job_name: sturdy_shelf_parameter_gallery

gallery:
  columns: 2
  target_width_px: 1920
  target_height_px: 1440
  margin_px: 0
  gutter_px: 4
  title_height_px: 60
  title_font_size_px: 60

variants:
- name: Slim_NoTexture
  set:
    scene.objects[0].model.defines.shelf_type: Slim
    scene.objects[0].model.defines.add_texture: false
    scene.objects[0].model.defines.horizontal_grids: 2
    scene.objects[0].model.defines.depth_grids: 2

- name: Slim_NoTexture_NoEdges
  set:
    scene.objects[0].model.defines.shelf_type: Slim
    scene.objects[0].model.defines.add_texture: false
    scene.objects[0].model.defines.add_right_edge: false
    scene.objects[0].model.defines.add_left_edge: false
    scene.objects[0].model.defines.add_front_edge: false
    scene.objects[0].model.defines.horizontal_grids: 2
    scene.objects[0].model.defines.depth_grids: 2

- name: Standard_NoTexture
  set:
    # scene.objects[0].model.defines.shelf_type: Slim
    scene.objects[0].model.defines.add_texture: false
    scene.objects[0].model.defines.horizontal_grids: 2
    scene.objects[0].model.defines.depth_grids: 2

- name: Split_Left_NoTexture
  set:
    scene.objects[0].model.defines.add_texture: false
    scene.objects[0].model.defines.add_right_connector_holes: true
    scene.objects[0].model.defines.add_right_edge: false
    scene.objects[0].model.defines.horizontal_grids: 2
    scene.objects[0].model.defines.depth_grids: 2
