$schema: ../schemas/annotation-render-config.schema.json
extends: base_scene.yaml
variant_name: openconnect_clamshell_holder_default
job_name: clamshell_holder_scene_default
scene:
  objects:
  - id: model
    model:
      scad_file: openconnect_clamshell_holder.scad
      defines:
        item_width: 164
        item_height: 60
        item_depth: 30
        item_corner_rounding: 8
        generate_holder_part: Both
        holder_slot_position: Top
        holder_slot_column_limit: 1
    transform:
      location_mm: [0, "-(item_height / 2 + og_standard_thickness)", 0]
      rotation_deg: [-90, 0, 0]
      scale:
        $constant: blender_scene_scale_vector
render:
  fit_margin: 0.1
annotations:
  style:
    $constant: default_annotation_style
    colors:
      item_width:
        $constant: annotation_color_black
      item_height:
        $constant: annotation_color_black
  aliases:
    holder_slot_position: slot_position
    item_corner_rounding_extent: item_corner_rounding
  # chains:
  # - ids: [item_width]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 30
  # - ids: [item_height]
  #   display_offset_mm: [8, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 28
  # - ids: [item_depth]
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 24
  # - ids: [front_opening_side_margin]
  #   optional: true
  #   display_offset_mm: [0, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 24
  # - ids: [front_opening_end_margin]
  #   optional: true
  #   display_offset_mm: [8, 0, 0]
  #   line_offset_px: 0
  #   label_offset_px: 24
  # angle_radius_callouts:
  # - id: item_corner_rounding_fillet
  #   arc_id: item_corner_rounding_extent
  #   radius_id: item_corner_rounding
  #   angle_id: item_corner_rounding
  #   optional: true
  #   show_angle_label: false
  #   radius_label_offset_px: 36
  #   angle_fill_alpha: 28
  image_labels:
  - $constant: bottom_image_label
    id: holder_slot_column_limit
    show_value: true
    value_color:
      $constant: annotation_color_blue
    font_size_px:
      $constant: annotation_title_font_size_px
